### ISSUE TITLE
Data and notification streams are not found

### ISSUE THREAD

**Issue by teemuloijas** [PANTHEONtech/lighty-core#391]
When using OpenDaylight, I'm able to open and use data and notification streams.
First opening the stream with POST request: 'http://localhost:8181/restconf/operations/sal-remote:create-data-change-event-subscription'.
After that using GET with the url that the previous request has returned. And after that opening the WebSocket connection with the url that the GET request returns.

When using Lighty, I'm able to open the stream using the POST request. It returns the stream name, but the stream can not be found using the GET request (404). 
The stream seems to disappear. What could be causing this? Or what's the difference in this case between ODL and Lighty?

**Comment by RottingApple** [comment]
Hello,

could you define which the contoller you're using? I couldn't find a controller which would support create-data-change-event-subscription rpc.

**Comment by ihrasko** [comment]
Hi @teemuloijas 

RESTCONF notifications are not supported right now in Lighty.

Please see #531 (I assume that you have added missing modules by yourself) and #532.
